export const userConstants = {
  LOGIN_REQUEST: 'user/LOGIN_REQUEST',
  LOGIN_REQUEST_SUCCESS: 'user/LOGIN_REQUEST_SUCCESS',
  LOGIN_REQUEST_ERROR: 'user/LOGIN_REQUEST_ERROR',

  REGISTER_USER: 'user/REGISTER_USER',
  REGISTER_USER_SUCCESS: 'user/REGISTER_USER_SUCCESS',
  REGISTER_USER_ERROR: 'user/REGISTER_USER_ERROR',
  AUTH_USER: 'user/AUTH_USER',
  AUTH_USER_SUCCESS: 'user/AUTH_USER_SUCCESS',
  AUTH_USER_ERROR: 'user/AUTH_USER_ERROR',
  CLEAR_USER: 'user/CLEAR_USER',
  KEEP_USER_LOGGED_IN: 'user/KEEP_USER_LOGGED_IN',
};
