export const userConstants = {
  LOGIN_REQUEST: "user/LOGIN_REQUEST",
  LOGIN_REQUEST_SUCCESS: "user/LOGIN_REQUEST_SUCCESS",
  LOGIN_REQUEST_ERROR: "user/LOGIN_REQUEST_ERROR",

  REGISTER_REQUEST: "user/REGISTER_REQUEST",
  REGISTER_REQUEST_SUCCESS: "user/REGISTER_REQUEST_SUCCESS",
  REGISTER_REQUEST_ERROR: "user/REGISTER_REQUEST_ERROR",

  LOGOUT_REQUEST: "user/LOGOUT_REQUEST",
  LOGOUT_REQUEST_SUCCESS: "user/LOGOUT_REQUEST_SUCCESS",
  LOGOUT_REQUEST_ERROR: "user/LOGOUT_REQUEST_ERROR",

  AUTH_USER: "user/AUTH_USER",
  AUTH_USER_SUCCESS: "user/AUTH_USER_SUCCESS",
  AUTH_USER_ERROR: "user/AUTH_USER_ERROR",
  CLEAR_USER: "user/CLEAR_USER",
  CHECK_USER_IS_LOGGED_IN: "user/CHECK_USER_IS_LOGGED_IN",
};
